# Generated by Django 5.1.1 on 2024-09-19 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='anoop',
        ),
    ]
